// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package post is a generated GoMock package.
package post

import (
	models "caching_web_server/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// Mockservice is a mock of service interface.
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
}

// MockserviceMockRecorder is the mock recorder for Mockservice.
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance.
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// SaveDocument mocks base method.
func (m *Mockservice) SaveDocument(ctx context.Context, login string, meta models.Meta, jsonData, file []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDocument", ctx, login, meta, jsonData, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveDocument indicates an expected call of SaveDocument.
func (mr *MockserviceMockRecorder) SaveDocument(ctx, login, meta, jsonData, file interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDocument", reflect.TypeOf((*Mockservice)(nil).SaveDocument), ctx, login, meta, jsonData, file)
}
